import type {Actor,Hazard,Point,Save} from '../types';
import {hasTalent,inSlot,maxHp,maxStamina} from '../systems/progression';
export const distance=(a:Point,b:Point)=>Math.hypot(a.x-b.x,a.y-b.y);
export const angleTo=(a:Point,b:Point)=>Math.atan2(b.y-a.y,b.x-a.x);
export const angleDiff=(a:number,b:number)=>Math.atan2(Math.sin(a-b),Math.cos(a-b));
export function actor(id:string,kind:Actor['kind'],p:Point,hp:number,boss=false):Actor{return {...p,id,kind,hp,maxHp:hp,stamina:100,angle:0,state:'idle',timer:0,attackIndex:0,phase:0,boss,spawn:{...p},target:{...p},speed:kind==='warg'?115:kind==='spider'?100:kind==='troll'?65:85,radius:boss?27:kind==='troll'?21:13,invuln:0,burn:0,burnDps:4,slowFactor:.7,poison:0,poisonStacks:0,slow:0,root:0,silence:0,barrier:0,echo:0,guard:0,counter:0,flash:0,deadTime:0,combo:0,attackCd:0,dodgeCd:0,regenDelay:0,flasks:3,cooldowns:{}};}
export function hitHazard(h:Hazard,p:Point,radius=0){const d=distance(h,p),a=angleTo(h,p);switch(h.shape){case 'circle':return d<h.radius+radius;case 'ring':return Math.abs(d-h.radius)<h.width+radius&&Math.abs(angleDiff(a,h.angle))>.4;case 'cone':return d<h.radius+radius&&Math.abs(angleDiff(a,h.angle))<h.width/2;case 'line':{const along=(p.x-h.x)*Math.cos(h.angle)+(p.y-h.y)*Math.sin(h.angle),cross=Math.abs(-(p.x-h.x)*Math.sin(h.angle)+(p.y-h.y)*Math.cos(h.angle));return along>=-radius&&along<h.length+radius&&cross<h.width+radius;}}}
export function incomingDamage(s:Save,base:number,guard=false){const difficulty={Story:.62,Adventurer:1,Veteran:1.28}[s.settings.difficulty];let reduction=(hasTalent(s,'guardian2')?.03:0)+(hasTalent(s,'guardian9')?.02:0)+(inSlot(s,'stoneward','support')?.05:0);if(guard)reduction+=.68+(hasTalent(s,'guardian1')?.04:0)+(inSlot(s,'iron-oath','support')?.08:0);return Math.max(1,base*difficulty*(1-Math.min(.85,reduction)));}
export function refillPlayer(s:Save,p:Actor){p.maxHp=maxHp(s);p.hp=p.maxHp;p.stamina=maxStamina(s);p.flasks=3;p.barrier=0;p.burn=0;p.poison=0;p.poisonStacks=0;p.silence=0;p.invuln=1;}
export function tickCooldowns(a:Actor,dt:number){for(const k of ['attackCd','dodgeCd','regenDelay','invuln','flash','root','slow','silence','echo','counter'] as const)a[k]=Math.max(0,a[k]-dt);for(const k of Object.keys(a.cooldowns) as (keyof typeof a.cooldowns)[])a.cooldowns[k]=Math.max(0,(a.cooldowns[k]??0)-dt);}
