import type {RingDef,RingId} from '../types';
export const RINGS:RingDef[]=[
{id:'ember',name:'Ember',stage:1,color:0xce7144,icon:'flame',cooldown:8,power:30,range:150,active:'A 100° fire arc deals 30 damage and burns for 12 more over 3 seconds. Ignites marked brambles.',support:'Weapon hits add 2 burn damage per second for 2 seconds. Refreshes; does not stack.',home:'A warm brazier blooms. Winter enemy damage is reduced by 3%.',lore:'The ring-smith’s apprentice kept one coal when all the furnaces went dark.',ev4:'Arc widens to 120°. Burn lasts 4 seconds.',ev7:'Leaves a 2-second ember patch; one pulse per target, 12 damage.',clue:'A traveller’s coffer on Ashen Road.'},
{id:'stoneward',name:'Stoneward',stage:2,color:0xc5b28b,icon:'stone',cooldown:14,power:40,range:100,active:'A barrier absorbs 40 damage for 5 seconds. Breaking or expiring bursts for 18 nearby damage.',support:'Take 5% less direct damage.',home:'A stone ward surrounds the chest. Start defence waves with a 20-point barrier.',lore:'A ring cut from a threshold that never yielded to winter.',ev4:'Barrier rises by an additional 10 points.',ev7:'The burst briefly staggers ordinary enemies for 0.7 seconds.',clue:'Defeat Kruk Hookhand at Broken Mill.'},
{id:'windstep',name:'Windstep',stage:4,color:0xafcab4,icon:'wind',cooldown:10,power:28,range:185,active:'Dash 170 units in your aim direction with 0.18 seconds of safety; a cutting gust deals 28 damage.',support:'Movement speed increases by 5%.',home:'Banners move in the wind. Optional cache positions appear on the mission map.',lore:'A scout tied a promise to the west wind and never walked alone again.',ev4:'Dash reaches 195 units, respecting walls.',ev7:'Gust hits up to 5 targets instead of 3.',clue:'Defeat Greyfang at Wolf Pass.'},
{id:'thornwake',name:'Thornwake',stage:6,color:0x86a56c,icon:'thorn',cooldown:13,power:18,range:150,active:'Place a root patch. Deals 18 damage and roots ordinary enemies for 2 seconds; bosses slow by 15%.',support:'Regenerate 2 extra stamina per second.',home:'The garden flourishes. First-clear expeditions grant 3 extra wood, capped at 3.',lore:'Even the oldest thorn remembers being a flower.',ev4:'Patch radius increases from 85 to 100.',ev7:'Root duration becomes 2.5 seconds; bosses remain capped at 15% slow.',clue:'Free the scouts on Thornwood Trail.'},
{id:'dawnward',name:'Dawnward',stage:8,color:0xf0da91,icon:'sun',cooldown:12,power:32,range:160,active:'A light pulse deals 32 damage and breaks visible optional dark wards. Reveals authored inscriptions.',support:'Flasks recover 8 additional HP.',home:'Lanterns brighten. Clues identify the closest optional secret.',lore:'Its maker never saw the sun, but trusted that it would return.',ev4:'Pulse radius increases by 15 units.',ev7:'Disrupts an ordinary enemy’s telegraph once per cast.',clue:'Restore the Sunken Shrine.'},
{id:'venomcoil',name:'Venomcoil',stage:9,color:0xa4b965,icon:'venom',cooldown:9,power:20,range:450,active:'Fire a venom dart for 20 damage. Poison deals 4 per second for 4 seconds, capped at 3 stacks.',support:'Weapon strikes apply a 5% slow for 1 second.',home:'Glass covers the garden. Flasks recover 5 additional HP.',lore:'A gardener’s answer to the things that ate the roots.',ev4:'Poison lasts 5 seconds; still capped at 3 stacks.',ev7:'Dart pierces one additional enemy, respecting walls.',clue:'Silence the Hush-Caller in Whispering Grove.'},
{id:'frostwake',name:'Frostwake',stage:11,color:0x95b6c6,icon:'snow',cooldown:11,power:30,range:155,active:'A frost cone deals 30 damage and slows by 30% for 3 seconds. Freezes marked optional water.',support:'Dodge costs 3 less stamina.',home:'Frost lanterns shine. Winter movement gains 3%.',lore:'Water held still to let a stranger cross.',ev4:'Cone widens from 85° to 105°.',ev7:'Ordinary foes freeze for 0.7 seconds; bosses only slow.',clue:'Reopen the Old Quarry.'},
{id:'iron-oath',name:'Iron Oath',stage:13,color:0xbcc4bb,icon:'shield',cooldown:12,power:38,range:130,active:'Brace for 1.3 seconds, reducing damage by 70%. A hit within 0.45 seconds retaliates for 38 and staggers.',support:'Guard reduces a further 8% damage; capped at 85% total.',home:'Iron banners strengthen barricades. Defence damage taken falls by 5%.',lore:'An oath is a thing held when the hand is empty.',ev4:'The perfect defence window increases to 0.55 seconds.',ev7:'Retaliation reaches 3 enemies within 130 units.',clue:'Secure the Icebridge.'},
{id:'echo',name:'Echo',stage:14,color:0xb8a2cb,icon:'echo',cooldown:10,power:0,range:170,active:'Your next weapon attack within 5 seconds repeats once at 45% damage. No ring or synergy recursion.',support:'Weapon recovery is 5% faster.',home:'An animated practice dummy measures your last hit and peak damage.',lore:'A hammer’s last note, kept by a hall that missed its maker.',ev4:'Repeat damage increases to 50%.',ev7:'Repeat damage increases to 55%, the hard cap.',clue:'Recover the records in Hall of Anvils.'},
{id:'stormcall',name:'Stormcall',stage:17,color:0xbacde3,icon:'bolt',cooldown:13,power:34,range:250,active:'Lightning jumps to 3 visible foes within 250 units for 34 damage each. Wet targets take 10% more.',support:'Ring cooldowns are reduced by 5%.',home:'The watchtower catches quiet lightning. Show all optional cache positions.',lore:'The first storm after the siege rang like bells of relief.',ev4:'Chain cap becomes 4 targets.',ev7:'Chain cap becomes 5 targets; jumps never trigger further chains.',clue:'Disable the Siegeworks.'},
{id:'duskveil',name:'Duskveil',stage:21,color:0xab9db8,icon:'moon',cooldown:11,power:20,range:180,active:'Blink up to 160 units along a clear path. A shadow distracts ordinary enemies for 2 seconds and strikes once for 20.',support:'Dodge cooldown is 8% shorter.',home:'A shadow garden reveals the season’s alternate-route clue.',lore:'A ring for those who crossed a dark room to open its window.',ev4:'Shadow lasts 2.5 seconds.',ev7:'Shadow’s one strike gains a 0.5-second ordinary-enemy stagger.',clue:'Find the name-stone in Mirror Barrows.'},
{id:'last-hearth',name:'Last Hearth',stage:25,color:0xf2d298,icon:'hearth',cooldown:16,power:20,range:110,active:'Create a 4-second shelter circle. Intercept up to 5 enemy projectiles and recover 20 HP once.',support:'Maximum health increases by 6%.',home:'A luminous central beacon illuminates the roofs and your six trophies.',lore:'Not a ring to rule. A ring to leave a light on.',ev4:'Shelter intercepts 7 projectiles.',ev7:'Shelter lasts 5 seconds and intercepts at most 9 projectiles.',clue:'Drive the Nameless Nazgûl from Black Causeway.'}
];
export const ringById=Object.fromEntries(RINGS.map(r=>[r.id,r])) as Record<RingId,RingDef>;
export const SYNERGIES=[
{id:'wildfire',pair:['ember','windstep'] as RingId[],name:'Wildfire wind',text:'Cast Windstep while a foe burns: spread a 12-damage ember to up to 3 nearby foes. 8-second internal cooldown.',cooldown:8},
{id:'shatter',pair:['frostwake','stormcall'] as RingId[],name:'Winter thunder',text:'Stormcall against a slowed foe adds one 16-damage shatter pulse to at most 3 foes. 10-second internal cooldown.',cooldown:10},
{id:'nightgarden',pair:['thornwake','venomcoil'] as RingId[],name:'Bitter roots',text:'Thornwake poisons rooted foes for one stack. Maximum 4 targets; 10-second internal cooldown.',cooldown:10},
{id:'bastion',pair:['stoneward','iron-oath'] as RingId[],name:'The held promise',text:'A successful Iron Oath counter with Stoneward grants a 20-point barrier and a 15-damage retaliation. 12-second internal cooldown.',cooldown:12},
{id:'aftermath',pair:['echo','duskveil'] as RingId[],name:'After the shadow',text:'Duskveil while Echo is ready makes one delayed 18-damage shadow strike on up to 3 foes. 10-second internal cooldown.',cooldown:10},
{id:'kindled',pair:['dawnward','last-hearth'] as RingId[],name:'A light for everyone',text:'Dawnward within shelter heals 10 HP and enlarges its radius by 20, once per shelter. 14-second internal cooldown.',cooldown:14}
];
