import test from 'node:test';
import assert from 'node:assert/strict';
import {Engine} from '../src/game/engine';
import {freshSave,SaveStore,validateSave} from '../src/systems/saves';
import {actor,distance} from '../src/game/combat';
import {canopyTarget,easeAlpha} from '../src/world/nature';
import {CELL,canStand,makeMap} from '../src/world/maps';
import {STAGES} from '../src/content/stages';
import {narrative} from '../src/content/story';
function encounter(){const e=new Engine(freshSave(),new SaveStore());e.loadMission(1,true);e.beginBoss();e.enemies=[];Object.assign(e.player,e.map.arena);e.player.angle=0;e.player.invuln=0;const target=actor('target','orc',{x:e.player.x+60,y:e.player.y},1000);e.enemies=[target];return {e,target};}
test('Sword damage lands at contact, once, with a harmless visual trail',()=>{const {e,target}=encounter();e.attack();assert.equal(target.hp,1000);e.tickStrike(.05);assert.equal(target.hp,1000);e.tickStrike(.04);const hp=target.hp;assert.ok(hp<1000);e.tickStrike(.05);assert.equal(target.hp,hp);assert.ok(e.hazards.some(h=>h.kind==='slash'&&h.damage===0));});
test('Bow release is delayed, axe has a longer anticipation and dodge cancels an unlanded strike',()=>{for(const family of ['bow','axe'] as const){const {e,target}=encounter();e.save.inventory[0].family=family;e.charge=1.5;e.attack(true);assert.equal(e.projectiles.length,0);e.tickStrike(.1);assert.equal(target.hp,1000);assert.equal(e.projectiles.length,0);assert.equal(e.strike!.impact,family==='bow'?.12:.18);if(family==='bow'){e.tickStrike(.03);assert.equal(e.projectiles.length,1);}else{e.dodge();e.tickStrike(.2);assert.equal(e.strike,null);assert.equal(target.hp,1000);}}});
test('Pausing freezes the strike and cooldown; attacking at zero stamina stays available',()=>{const {e,target}=encounter();e.player.stamina=0;e.attack();const cd=e.player.attackCd;e.pause();for(let i=0;i<60;i++)e.tick(1/60);assert.equal(e.strike!.age,0);assert.equal(target.hp,1000);assert.equal(e.player.attackCd,cd);});
test('Charges travel continuously and do not damage the far end before arrival',()=>{const {e,target:b}=encounter();Object.assign(b,e.map.arena);Object.assign(e.player,{x:b.x+230,y:b.y});b.target={x:e.player.x,y:e.player.y};b.angle=0;b.state='attack';e.telegraph(b,'charge',0);e.performAttack(b,'charge');const before={x:b.x,y:b.y};assert.equal(distance(b,before),0);e.hazardTick(.01);assert.equal(e.player.hp,e.player.maxHp);e.enemyTick(b,1/60);assert.ok(distance(b,before)>0&&distance(b,before)<20);for(let i=0;i<20;i++){e.enemyTick(b,1/60);e.hazardTick(1/60);}assert.ok(e.player.hp<e.player.maxHp);});
test('Leap damage waits for landing and its target is within reachable travel distance',()=>{const {e,target:b}=encounter();b.target={x:b.x+700,y:b.y};b.angle=0;e.telegraph(b,'leap',.7);const h=e.hazards.find(h=>h.kind==='leap')!;assert.ok(h.delay>=1.07);assert.ok(distance(b,h)<=330.01);assert.ok(canStand(e.map,h,b.radius));});
test('Canopies retain at least 48% opacity, fade only across the head, and ease independently of frame rate',()=>{const tree={x:100,y:200,width:150,height:220};assert.equal(canopyTarget(tree,{x:100,y:150}),.48);assert.equal(canopyTarget(tree,{x:100,y:230}),1);assert.equal(canopyTarget(tree,{x:400,y:150}),1);let a=1,b=1;for(let i=0;i<60;i++)a=easeAlpha(a,.48,1/60);for(let i=0;i<30;i++)b=easeAlpha(b,.48,1/30);assert.ok(a>=.48&&Math.abs(a-b)<1e-10);});
test('All thirty maps have rivers, natural landmarks and traversable bridge decks',()=>{for(const stage of STAGES){const m=makeMap(stage,'Spring');assert.ok(m.river&&m.river.points.length>10);assert.ok(m.props.some(p=>p.kind==='boulder'||p.kind==='outcrop'));let bridges=0;for(let y=0;y<m.height;y++)for(let x=0;x<m.width;x++)if(m.tiles[y][x]===5){bridges++;assert.ok(canStand(m,{x:(x+.5)*CELL,y:(y+.5)*CELL},0));}assert.ok(bridges>0,'stage '+stage.id);}});
test('New games open a paused prologue; acknowledgement is one-time and old saves remain valid',()=>{const s=freshSave(),e=new Engine(s,new SaveStore());e.presentationEnabled=true;e.loadMission(1);assert.equal(e.state,'STORY');assert.equal(e.storyId,'prologue');const clock=e.clock;e.tick(10);assert.equal(e.clock,clock);assert.ok(!s.claimed.includes('story-prologue'));e.finishStory();assert.equal(e.state,'EXPLORING');assert.equal(s.claimed.filter(x=>x==='story-prologue').length,1);e.loadMission(1);assert.equal(e.state,'EXPLORING');assert.doesNotThrow(()=>validateSave(s));assert.doesNotThrow(()=>validateSave(freshSave()));});
test('Narrative spans six chapters and both endings; epilogues keep the campaign playable',()=>{for(let i=0;i<6;i++){assert.ok(narrative['chapter-'+i]?.length);assert.ok(narrative['return-'+i]?.length);}for(const ending of ['hearth','valley'] as const){const {e}=encounter();e.presentationEnabled=true;e.save.cleared=Array.from({length:30},(_,i)=>i+1);e.finishEnding(ending);assert.equal(e.state,'STORY');assert.equal(e.storyId,'ending-'+ending);e.finishStory();assert.equal(e.state,'STAGE_COMPLETE');assert.equal(e.save.ending,ending);assert.doesNotThrow(()=>validateSave(e.save));}});
