import type {Engine} from '../game/engine';
import type {WorldScene} from '../game/scene';
import type {Interface} from '../ui/ui';
import {freshSave,SaveStore} from '../systems/saves';
import {RINGS} from '../content/rings';
import {STAGES} from '../content/stages';
import {firstClearReward,credit} from '../systems/economy';
import {addXp,xpThreshold,rankCap,makeItem} from '../systems/progression';
import type {Save} from '../types';
export function fixtureSave(stage=1):Save{const s=freshSave();for(let i=1;i<stage;i++){s.cleared.push(i);credit(s,firstClearReward(i));addXp(s,xpThreshold(i));}for(const r of RINGS)if(r.stage<stage)s.rings[r.id]=rankCap(s.level);s.assignments={active1:stage>1?'ember':undefined,active2:stage>5?'stoneward':undefined};s.assignments=Object.fromEntries(Object.entries(s.assignments).filter(([,v])=>v));s.wallet.gold+=5000;s.wallet.shards+=100;s.checkpoint.stage=stage;s.checkpoint.boss=true;return s;}
export function installFixtures(e:Engine,scene:WorldScene,ui:Interface){if(!import.meta.env.DEV)return;const run=(stage:number,boss=true)=>{e.presentationEnabled=false;const memoryStore=new SaveStore();memoryStore.onStatus=()=>{};e.store=memoryStore;e.save=fixtureSave(stage);e.loadMission(stage,boss,false);ui.panel='';ui.hideModal();if(boss)e.beginBoss();};
 const api={stage:run,home:()=>{e.presentationEnabled=false;e.store=new SaveStore();e.store.onStatus=()=>{};e.save=fixtureSave(30);e.save.cleared.push(30);e.save.ending='valley';e.save.residents=['smith','scout','mason','gardener','healer','chronicler'];e.loadHome();},allRings:()=>{for(const r of RINGS)e.save.rings[r.id]=rankCap(e.save.level);},state:()=>({state:e.state,stage:e.stage.id,level:e.save.level,hp:e.player.hp,stamina:e.player.stamina,player:{x:e.player.x,y:e.player.y},enemies:e.enemies.map(a=>({id:a.id,x:a.x,y:a.y,hp:a.hp,phase:a.phase,state:a.state})),hazards:e.hazards.length,objects:e.objects.map(o=>({id:o.id,x:o.x,y:o.y,done:o.done,kind:o.kind})),save:e.save,seconds:e.elapsed}),phase:(n:number)=>{const b=e.enemies.find(x=>x.boss);if(b)b.hp=b.maxHp*(n===1?.46:.27);},teleport:(x:number,y:number)=>{e.player.x=x;e.player.y=y;},defeat:()=>{e.player.invuln=0;e.damagePlayer(99999);},win:()=>{const b=e.enemies.find(x=>x.boss);if(b){for(const o of e.objects)if(o.kind==='anchor')o.done=true;e.damageEnemy(b,b.maxHp*5,'fixture');}},act:(name:string)=>{if(name==='attack')e.attack();if(name==='dodge')e.dodge();if(name==='interact')e.interact();if(name==='ring1')e.ring(1);if(name==='ring2')e.ring(2);},fps:()=>scene.game.loop.actualFps,engine:e,scene,ui};
 Object.defineProperty(window,'__HEARTH_DEV__',{value:api,configurable:true});
 window.addEventListener('message',ev=>{if(ev.origin!==location.origin||ev.data?.type!=='hearth-qa-touch')return;ui.close();e.store=new SaveStore('last-hearth-qa-mobile');e.store.onStatus=()=>{};e.loadHome();const stick=document.getElementById('joystick')!,attack=document.querySelector<HTMLElement>('[data-touch=attack]')!,b=stick.getBoundingClientRect(),p={x:e.player.x,y:e.player.y};let strikes=0;const listener=(a:any)=>{if(a.type==='sound'&&a.key==='swing')strikes++;};e.events.push(listener);stick.dispatchEvent(new PointerEvent('pointerdown',{pointerId:101,pointerType:'touch',clientX:b.left+b.width/2+35,clientY:b.top+b.height/2,bubbles:true}));attack.dispatchEvent(new PointerEvent('pointerdown',{pointerId:102,pointerType:'touch',bubbles:true}));setTimeout(()=>{stick.dispatchEvent(new PointerEvent('pointerup',{pointerId:101,pointerType:'touch'}));attack.dispatchEvent(new PointerEvent('pointerup',{pointerId:102,pointerType:'touch'}));e.events=e.events.filter(f=>f!==listener);window.parent.postMessage({type:'hearth-qa-result',text:'390 × 844 iframe viewport\nSynthetic simultaneous touch\nMovement: '+Math.hypot(e.player.x-p.x,e.player.y-p.y).toFixed(1)+' world units\nStrikes: '+strikes+'\nInput released: '+!e.attackHeld+'\nFPS: '+scene.game.loop.actualFps.toFixed(1)},location.origin);},1500);});
 const params=new URLSearchParams(location.search);if(params.has('fixture')){const s=Number(params.get('fixture'));if(s>=1&&s<=30)run(s,params.get('boss')!=='0');}
 if(params.has('qa')){e.store=new SaveStore('last-hearth-qa');e.store.onStatus=()=>{};
  const existing=document.getElementById('qa-tools');existing?.remove();const box=document.createElement('div');box.id='qa-tools';box.style.cssText='position:fixed;right:8px;top:215px;z-index:200;background:#14221df2;color:#e4d8bc;border:1px solid #c2a264;padding:10px;width:210px;font:11px system-ui;max-height:65vh;overflow:auto;pointer-events:auto';box.innerHTML=`<b>DEVELOPMENT FIXTURES</b><p>Isolated from player saves.</p><select id="qa-stage" style="width:100%;height:32px;background:#203b2d;color:white">${STAGES.map(s=>`<option value="${s.id}">${s.id} · ${s.boss}</option>`).join('')}</select><div id="qa-buttons" style="display:grid;grid-template-columns:1fr 1fr;gap:5px;margin-top:8px"></div><pre id="qa-readout" style="white-space:pre-wrap;font-size:10px"></pre>`;document.body.append(box);
  const button=(name:string,fn:()=>void)=>{const b=document.createElement('button');b.textContent=name;b.style.cssText='font-size:10px;min-height:36px;padding:5px';b.onclick=fn;box.querySelector('#qa-buttons')!.append(b);};const output=(text:string)=>{box.querySelector('#qa-readout')!.textContent=text;};window.addEventListener('message',ev=>{if(ev.origin===location.origin&&ev.data?.type==='hearth-qa-result')output(ev.data.text);});
  button('Load boss',()=>run(Number((box.querySelector('#qa-stage') as HTMLSelectElement).value)));button('Phase 2',()=>api.phase(1));button('Phase 3',()=>api.phase(2));button('Boss victory',()=>api.win());button('Death',()=>api.defeat());button('Home fixture',()=>api.home());button('Fresh fixture',()=>{e.store=new SaveStore('last-hearth-qa');e.store.onStatus=()=>{};e.save=freshSave();e.loadMission(1);ui.panel='';ui.hideModal();});
  button('First ring',()=>{const o=e.objects.find(o=>o.kind==='ring');if(o){e.player.x=o.x+38;e.player.y=o.y;e.enemies=[];e.interact();}});button('Boss entrance',()=>{e.enemies=[];for(const o of e.objects)if(o.kind==='objective')e.completeObjective(o);if(e.stage.id===1&&!e.save.rings.ember){e.save.rings.ember=1;e.save.assignments.active1='ember';}Object.assign(e.player,e.map.checkpoint);e.interact();});
  button('All rings',()=>api.allRings());button('Mobile layout',()=>{let frame=document.getElementById('qa-phone') as HTMLIFrameElement|null;if(frame){frame.remove();document.getElementById('ui')!.style.visibility='';document.getElementById('game')!.style.visibility='';box.style.left='';box.style.right='8px';e.resume();return;}e.pause();document.getElementById('ui')!.style.visibility='hidden';document.getElementById('game')!.style.visibility='hidden';frame=document.createElement('iframe');frame.id='qa-phone';frame.src=location.pathname+'?mobilechild=1';frame.style.cssText='position:fixed;left:0;top:0;width:390px;height:844px;border:0;z-index:190;background:#171c1b';document.body.append(frame);box.style.left='410px';box.style.right='auto';});
  button('Touch regression',()=>{const phone=document.getElementById('qa-phone') as HTMLIFrameElement|null;if(phone){phone.contentWindow!.postMessage({type:'hearth-qa-touch'},location.origin);return;}ui.close();if(e.state!=='HOME')e.loadHome();const stick=document.getElementById('joystick')!,attack=document.querySelector<HTMLElement>('[data-touch=attack]')!,bounds=stick.getBoundingClientRect();const before={x:e.player.x,y:e.player.y};let strikes=0;const listener=(ev:any)=>{if(ev.type==='sound'&&ev.key==='swing')strikes++;};e.events.push(listener);stick.dispatchEvent(new PointerEvent('pointerdown',{pointerId:101,pointerType:'touch',clientX:bounds.left+bounds.width/2+30,clientY:bounds.top+bounds.height/2,bubbles:true}));attack.dispatchEvent(new PointerEvent('pointerdown',{pointerId:102,pointerType:'touch',bubbles:true}));setTimeout(()=>{stick.dispatchEvent(new PointerEvent('pointerup',{pointerId:101,pointerType:'touch'}));attack.dispatchEvent(new PointerEvent('pointerup',{pointerId:102,pointerType:'touch'}));e.events=e.events.filter(x=>x!==listener);output(`Synthetic two-pointer test\nMoved: ${Math.hypot(e.player.x-before.x,e.player.y-before.y).toFixed(1)} world units\nWeapon strikes: ${strikes}\nInput cleared: ${!e.attackHeld}`);},1200);});
  button('Save roundtrip',async()=>{const db=new SaveStore('last-hearth-qa');await db.open();await db.put(e.save);const loaded=await db.get();output(`IndexedDB roundtrip: ${JSON.stringify(loaded?.wallet)===JSON.stringify(e.save.wallet)&&loaded?.level===e.save.level?'PASS':'FAIL'}\nLevel ${loaded?.level}\nRings ${Object.keys(loaded?.rings??{}).length}\nBuildings ${loaded?.buildings.length}\nBackup preserved: ${!!await db.get('backup')}`);});
  button('Sample FPS',()=>{const samples:number[]=[];let left=5;const interval=setInterval(()=>{samples.push(scene.game.loop.actualFps);left--;if(!left){clearInterval(interval);output(`Phaser actual FPS, 5s\nSamples: ${samples.map(n=>n.toFixed(1)).join(', ')}\nMean: ${(samples.reduce((a,b)=>a+b,0)/samples.length).toFixed(1)}\nCPU update: ${scene.cpuMs.toFixed(2)} ms\nVisibility: ${document.visibilityState} / focused ${document.hasFocus()}\nRenderer: ${scene.game.renderer?.type}\nViewport: ${scene.scale.width} × ${scene.scale.height}\n${navigator.userAgent}`);}},1000);});
  for(const [label,key] of [['Walk up','KeyW'],['Walk right','KeyD'],['Walk down','KeyS'],['Walk left','KeyA'],['Strike','KeyJ']] as const)button(label,()=>{window.dispatchEvent(new KeyboardEvent('keydown',{code:key}));setTimeout(()=>window.dispatchEvent(new KeyboardEvent('keyup',{code:key})),600);});
  button('Snapshot state',()=>output(JSON.stringify(api.state(),(k,v)=>['save','objects'].includes(k)?undefined:v,2)));button('Hide QA',()=>box.style.display='none');
 }
}
